import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
const publicSans = Public_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Beamdust",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={publicSans.className}>
        <Header />
        {children}
        </body>
    </html>
  );
}
